### ISSUE TITLE
How to initiate an audio call from bot to user?

### ISSUE THREAD

**Issue by SrilekhaT** [Microsoft/BotBuilder-V3#113]
Hi, 
Is it possible to initiate an audio call from Bot to the user? If yes, Could you please provide the sample code using nodejs.

**Comment by tdurnford** [comment]
This appears to be a duplicate of this [Stack Overflow question](https://stackoverflow.com/questions/54303517/how-to-initiate-an-audio-call-from-bot-to-user).

**Comment by tdurnford** [comment]
The official [Bot Framework Github](https://github.com/Microsoft/BotBuilder/blob/master/README.md) repos are the preferred platform for submitting **bug fixes** and **feature requests**, and the Microsoft Bot Framework team prefers that **how to** questions be submitted on [Stack Overflow](http://stackoverflow.com/search?q=%23botframework). Since you have already asked your question on Stack Overflow, we will help answer your [question](https://stackoverflow.com/questions/54303517/how-to-initiate-an-audio-call-from-bot-to-user) there. 

This appears to be a duplicate of this [Stack Overflow question](https://stackoverflow.com/questions/54303517/how-to-initiate-an-audio-call-from-bot-to-user).

**Comment by SrilekhaT** [comment]
Thanks for the update. Can you please answer the question in stack overflow.
