### ISSUE TITLE
FormBuilder ValidateResult Choices only works on emulator

### ISSUE THREAD

**Issue by ruisilva450** [Microsoft/BotBuilder-V3#115]
## Version
v3.20.1

## Describe the bug
I have a model with a FormBuilder with a field that asks a string that should contain a date, asks LUIS about the resolution of that date and if there are multiple resolutions it appends to ValidateResult Choices the possible answers for the user to pick. But this only works fine in the emulator. Skype and Teams were tested so far with error BadRequest on bubbling up to parent dialog.

## To Reproduce
1. FormBuilder with field of type string expecting to have "30-01-2019" when form is complete
2. Validate delegation to custom logic
3. Send response to LUIS to check for prebuild entity of type **datetimev2**
4. LUIS gives back 2+ resolutions for dates in the format of "dd-MM-yyyy"
5. For each resolution create choice and append it to ValidateResult.Choices
6. Return ValidateResult
7. Test in emulator: works
8. Test in Skype/MSTeams: don't work

## Expected behavior
Give the same options as the emulator renders

## Screenshots
Emulator:
![image](https://user-images.githubusercontent.com/5648218/52123753-ed159600-261e-11e9-9a84-e772d70a31b6.png)

Skype:
![image](https://user-images.githubusercontent.com/5648218/52123866-47aef200-261f-11e9-8612-0e2a16e21062.png)

## Additional context
```csharp
.Field(nameof(Date), validate: async (state, response) =>
{
    var result = new ValidateResult { IsValid = true, Value = response };

    var luisResult = await LuisLog.GetLuisResultAsync(this.EmailAddress, response as string);

    bool foundResult = false;
    bool parcialResult = false;

    foreach (var entity in luisResult.Entities)
    {
        if (!foundResult && !parcialResult)
        {
            switch (entity.Type)
            {
                case "builtin.datetimeV2.date":
                    if (JArray.Parse(JsonConvert.SerializeObject(entity.Resolution.Values.First())).Count > 1)
                    {
                        result.Choices = new List<Choice>();
                        foreach (var item in JArray.Parse(JsonConvert.SerializeObject(entity.Resolution.Values.First())))
                        {
                            result.Choices = result.Choices.Append(new Choice()
                            {
                                Value = item["value"].ToString(),
                                Description = new DescribeAttribute($"{item["value"].ToString()} ({ConversationHelpers.GetDayOfWeek(item["value"].ToString(), "yyyy-MM-dd")})", null, null, null, null),
                                Terms = new TermsAttribute(item["value"].ToString())
                            });
                        }

                        foundResult = false;
                        parcialResult = true;
                    }
                    else
                    {
                        result.Value = JArray.Parse(JsonConvert.SerializeObject(entity.Resolution.Values.First())).First()["value"].ToObject<DateTime>().ToString("dd-MM-yyyy");
                        parcialResult = true;
                        foundResult = true;
                    }
                    break;
                case "builtin.number":
                    var number = int.Parse(entity.Resolution.Values.First().ToString());
                    var date = new DateTime(DateTime.UtcNow.Year, DateTime.UtcNow.Month, number).ToString("dd-MM-yyyy");
                    result.Value = date;
                    parcialResult = true;
                    foundResult = true;
                    break;
                default:
                    break;
            }
        }
    }

    result.IsValid = foundResult;
    return result;
})
```

**Comment by Zerryth** [comment]
@ruisilva450 sent you an email. Please take a gander :)

**Comment by CoHealer** [comment]
@ruisilva450, @Zerryth requested you send over your bot to help in the investigation. Do you still need assistance and if so can you please send it over to her? Thx.

**Comment by Zerryth** [comment]
@ruisilva450 specifically can you share the code for what defines LuisLog, so I can run your code?

**Comment by ruisilva450** [comment]
Sorry for the delay. I'm trying to prepare a repo to reproduze this. Maybe this weekend.

**Comment by Zerryth** [comment]
@ruisilva450 sounds good. 

Right now I've set up a project on my own machine that points to the v3 SDK so I can debug into it locally.

However plugging your code into the formflow of the bot, there are certain members I don't have the definitions of
![image](https://user-images.githubusercontent.com/35248895/52878795-5e227680-3112-11e9-9794-340f6993d663.png)

I'll wait for your sharing and will dig further then

**Comment by ruisilva450** [comment]
@Zerryth sorry of the delay.

On this [repo](https://github.com/ruisilva450/FormBuilder_115) there is a showcase of this issue.

Remember that in the emulator it works "fine" but on other channels (skype e.g.) it just fails.
I say "fine" because it still shows a ```0``` before asking the right choice.

I also left a LUIS app credentials on ```web.config``` on purpose that is created to reproduce the same behaviour as my official one (portuguese language with ```datetimev2``` prebuilt entity).

You can test with "25 de janeiro" which is "25 of january" in english.

**Comment by Zerryth** [comment]
Excellent, I'll take a look

**Comment by Zerryth** [comment]
Just to update, I have reproduced the error, and trying to dig down into the reason

**Comment by Zerryth** [comment]
@ruisilva450 the issue seems to be something that underlying is channel-specific to Teams and Skype which requires "text" property of messages to not be empty.
___
# The breaking issue

Looking into Azure --> Your Bot --> Channels, with the code you gave plugged in directly, I got the following errors:

_Teams_
![image](https://user-images.githubusercontent.com/35248895/53769881-1d588a80-3e92-11e9-9fab-d6d504db5cc6.png)

_Skype_
![image](https://user-images.githubusercontent.com/35248895/53769900-2b0e1000-3e92-11e9-85b8-26274c3e5bd1.png)


Both Teams and Skype want the Activity message's text to not be empty, whereas emulator does not care:

![image](https://user-images.githubusercontent.com/35248895/53769991-627cbc80-3e92-11e9-8a4a-40ccd8eb23e9.png)
___
# The workaround

To overcome this requirement, @EricDahlvang help me find that **when giving a value to `ValidateResult.Feedback`, both Teams and Skype function properly** and give the clarification prompt for the date ambiguity.

_Right below line 83 in `FormBuilderTestModel.cs`_
Adding in `result.Feedback = "sometexthere";`

```
                    result.IsValid = foundResult;
                    result.Feedback = "sometexthere";
                    return result;

```

_Teams_
![image](https://user-images.githubusercontent.com/35248895/53770261-5a714c80-3e93-11e9-88f8-d64bbfbaac81.png)

_Skype_
![image](https://user-images.githubusercontent.com/35248895/53770294-6f4de000-3e93-11e9-86c3-1382a358ddb1.png)

I don't have access Teams'/Skype's code base, so I can't see what happens 100% under-the-hood on the channel side of things, however it does appear that each channel uses `ValidateResult.Feedback` to form the response message to the user.

Not being able to change their codebase from our team here on Bot Framework, I'll leave it to your creativity to decide how to build your bot to accommodate the text-required restriction for Teams/Skype :)
