### ISSUE TITLE
Remove mention text still does not work [Ref BotBuilder #3067]

### ISSUE THREAD

**Issue by tgckpg** [microsoft/BotBuilder-V3#123]
## Version
3.20.1

## Describe the bug
Please refer to this bug [#3067](https://github.com/Microsoft/BotBuilder/issues/3067) that was closed by repo changes.

I think what #3067 described was correct since the code shown in [here](https://github.com/Microsoft/BotBuilder-V3/blob/master/CSharp/Library/Microsoft.Bot.Connector.Shared/ActivityEx.cs#L482) does not contain any codes that removes the `<at id=...></at>` tag.

[bug]
[dotnet]

**Comment by EricDahlvang** [comment]
This issue is very specific to the Skype channel.  Until it fixed in either the connector service, or the sdk, the following is a workaround:

```cs
foreach (var mention in msg.GetMentions().Where(mention => mention.Mentioned.Id == msg.Recipient.Id))
{
    int index = mention.Text.IndexOf('>');
    var nextIndex = mention.Text.IndexOf('<', index);
    var mentionText = mention.Text.Substring(index + 1, nextIndex - index - 1);
    msg.Text = msg.Text.Replace(mentionText, "").Trim();
}
```

**Comment by tgckpg** [comment]
Thanks, for now I'll be using the workaround.

However the connector service. Is there a repo for it so we can open an issue over there for the fix?

**Comment by EricDahlvang** [comment]
Connector Service specific issues can be filed here: https://github.com/Microsoft/BotFramework-Services/issues

However, this issue also exists with BotBuilder V4: https://github.com/Microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Schema/ActivityExtensions.cs#L54

I'll consult the team to see if this is something we intend to address in the sdk.

**Comment by EricDahlvang** [comment]
Hey @cleemullins 

This particular issue also exists in the V4 implementation: https://github.com/Microsoft/BotBuilder-V3/issues/123 (same code)

The problem stems from the fact that the **Skype Connector Service** populates the Mention.Text like so:
`<at id=\"28:2bc5b54d-5d48-4ff1-bd25-03dcbb5ce918\">healthtest</at>`

While the activity.Text property has only the recipient name:
`healthtest`

This issue has been present for quite some time: https://github.com/Microsoft/BotBuilder/issues/3067  We have historically recommended the above workaround for the Skype channel specifically.  However, it seems this should be fixed in either the connector service itself, or add Skype specific code to the sdk (v3 and v4).  Do you have a recommendation?

**Comment by cleemullins** [comment]
Given the Skype Channel is no longer allowing new bots to be created, it seems the writing is one-the-wall for all things Skype+Bots. Teams is the replacement. 

I would bias towards "just use the workaround".
