### ISSUE TITLE
Is there any way in handling multiple entities in a single utterance dynamically 

### ISSUE THREAD

**Issue by vishmonne** [Microsoft/BotBuilder-V3#124]
**Bot info**
•	SDK Platform : Node.js
•	SDK Version : v3

**Issue Description**

I want to know if there is any way wherein we can dynamically get the entities in a single utterance for a intent instead of getting static like this 

 var answerEntity = builder.EntityRecognizer.findEntity(args.entities, 'entity_type');

Like the code should be dynamic enough to handle multiple entitites

**Comment by v-kydela** [comment]
@vishmonne - Can you explain a bit more about what the problem is?

If you just want to return multiple entities instead of one entity, you can use [builder.EntityRecognizer.findAllEntities](https://github.com/Microsoft/BotBuilder-V3/blob/master/Node/core/src/dialogs/EntityRecognizer.ts#L80)

Does that resolve your issue?

**Comment by v-kydela** [comment]
@vishmonne - Are you still working on this?

**Comment by CoHealer** [comment]
Ten days with no user input. @vishmonne if you still need help with this, please acknowledge and re-open.
