### ISSUE TITLE
Microsoft Teams shows generic logo when Bot joins a call

### ISSUE THREAD

**Issue by saraswat40** [microsoft/BotBuilder-V3#143]
We have a bot which can join an online meeting in Microsoft Teams. The bot manifest has a logo URL. The Bot as defined in Microsoft Azure (Branding) also has a logo specified. However, when you chat with the bot the Microsoft Teams chat shows a generic logo ( <..> ). When the Bot joins a call, a different generic logo shows up. Is there any way to show the Bot's logo in these scenarios?

**Comment by stevkan** [comment]
@saraswat40, I don't see logo as a manifest property when looking over the manifest [schema](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema). What you would want to use is the [icon](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema#icons) property to define which images are used in association with your bot.

```json
  "icons": {
    "outline": "image_32.png",
    "color": "image_192.png"
  }
```

Please look over my answer on Stack Overflow (located [here](https://stackoverflow.com/questions/55965099/refresh-teams-bot-icon-name/56048673#56048673)) as it is relevant to you. In short, Teams pulls the bot icon from either the manifest (and attached images) or from the Azure bot settings depending on the location of the bot icon in Teams (i.e. bot profile image vs. conversation image).

With respect to the conversation image (when the bot joins a call), it's likely producing a generic image because the icon property hasn't been set in the manifest.

Test it out and let me know any new questions you may have, if any.

Hope of help!

**Comment by saraswat40** [comment]
Hello,

Thanks for the response. The icons are defined correctly and they do show up in some places, but not when when the bot is in a call (only a big default alphabet in a circle shows up in the call window). The logoUrl is a property under the 'Manifest' section in the Azure > App Registrations > 'App' section. 

Thanks

**Comment by stevkan** [comment]
Teams uses a different manifest with its own schema for uploading a bot as an app and doesn't rely on the manifest located under App Registrations. Have you created the Teams manifest? If you haven't, look over this [doc](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/apps/apps-overview) as well as the links to 'Create the package for your Microsoft Teams app' and 'Bots'.

**Comment by saraswat40** [comment]
Yes, the teams manifest is correct and has the icons defined. They also show up correctly. Its only when the Bot is in a call, do we not see the icon. See screenshot.

![Screenshot from 2019-05-22 11-19-03](https://user-images.githubusercontent.com/3200933/58186896-c473e380-7c83-11e9-8e7e-d31c805ab6d8.png)

**Comment by stevkan** [comment]
Quick question: when you say the bot joins the call, do you mean a voice call or the chat window of the voice call or something different?

**Comment by saraswat40** [comment]
I mean a voice call via the calls REST API ( /beta/app/calls ). T

**Comment by stevkan** [comment]
Per my SO posting, did you try clearing your cache?  Also, is the result the same across users? For instance, you mentioned the icon changes between calls. Is the icon the same or different between users on the same call?

**Comment by stevkan** [comment]
Are you still needing help with this issue?

**Comment by stevkan** [comment]
Closing issue as resolved.
