### ISSUE TITLE
Extend v3 SDK to support Skills (DotNet)

### ISSUE THREAD

**Issue by clearab** [microsoft/BotBuilder-V3#181]
See the [rollup issue](https://github.com/microsoft/botframework-sdk/issues/5589) for details.

**Comment by EricDahlvang** [comment]
Closing, since the preview bits are on MyGet: 

https://botbuilder.myget.org/feed/botbuilder-v3-dotnet-daily/package/nuget/Microsoft.Bot.Builder/3.30.0

Three steps to convert a v3 dotnet bot to skill:
1)	Change MessageController’s BotAuthentication attribute to SkillBotAuthentication.
1)	Add AllowedCallers app setting to web.config (comma delimited list of skill host MicrosoftAppIds, or ‘*’ to allow all hosts).
1)	Add code to send skill host EndOfConversation when the skill is finished.
