### ISSUE TITLE
I am getting below error message very frequently on DirectLine Channel : 	There was an error sending this message to your bot: HTTP status code GatewayTimeout

### ISSUE THREAD

**Issue by saurav2107** [Microsoft/BotBuilder-V3#90]
I am getting below error in my Bot very frequently, There was an error sending this message to your bot: HTTP status code GatewayTimeout.

Mainly I see this issue with Direct Line (WebChat) it works fine for other channels.

Bot Framework Version: 3.16.1.38846

My Bot is deployed in Staging environment, we are planning to move the Bot to Production very soon, but this issue seems to be blocker as it counts under performance issue.

I am using Azure Cosmos DB as state storage.

![image](https://user-images.githubusercontent.com/1011594/49569911-3e751200-f95b-11e8-9a42-b296a8e4911b.png)

Please let me know if more information is required.
--

**Comment by CoHealer** [comment]
There was a deployment last night that resulted in some availability issues with Direct Line. Are you still seeing this issue?

**Comment by saurav2107** [comment]
I am still getting these issue, though the frequency is less:

![image](https://user-images.githubusercontent.com/1011594/49653833-1c16ed80-fa5c-11e8-98eb-0f58638f3d10.png)

Also, can you please let me know if there's any forum/place where you announce deployment details.

**Comment by saurav2107** [comment]
Hi @EricDahlvang I have sent the details through email, do let me know if you need more information.

**Comment by carlosscastro** [comment]
Hello @saurav2107,

Few follow up questions to understand more about your bot:

1. 504 suggests that this might not be even hitting your code on the bot. If you navigate to your bot endpoint in a web browser, what do you get? i.e. if your endpoint is https://mybot.mydomain.com/api/messages, try navigating to https://mybot.mydomain.com/ in your browser. Do you get a 200 OK? Or an error?
2. Do you have app insights or other instrumentation in your bot? To understand what is going on, this would be really helpful as otherwise we don't know what is going on in your bot.
3. Where are you hosting your bot? Is it an azure web app or is it an environment where you manage the network?
4. do you see this error on other channels?

**Comment by saurav2107** [comment]
Hi @carlosscastro,

Inline is the response to your follow up questions to understand more about bot:

504 suggests that this might not be even hitting your code on the bot. If you navigate to your bot endpoint in a web browser, what do you get? i.e. if your endpoint is https://mybot.mydomain.com/api/messages, try navigating to https://mybot.mydomain.com/ in your browser. Do you get a 200 OK? Or an error? **Yes I get 200 Ok, as i can see the default html page of my bot.**

Do you have app insights or other instrumentation in your bot? To understand what is going on, this would be really helpful as otherwise we don't know what is going on in your bot.  - **I have added Application Insight will be sending you the insight key through mail.**

Where are you hosting your bot? Is it an azure web app or is it an environment where you manage the network? **My Bot is hosted on Azure web app.**


Do you see this error on other channels? Do you use other channels or are you focused on DirectLine?
**Generally not, for now  I have two channels, DirectLine to cater web based chat Bot and Microsoft Teams.
I generally see this error on DirectLine.**

**Comment by saurav2107** [comment]
Hi @carlosscastro, unable to find your email, please let me know how can i send you application insight details.

**Comment by EricDahlvang** [comment]
Hi @saurav2107  

Carlos was not asking for you to send the Application Insights key, but rather for you to ensure that you have setup Application Insights in order to help you diagnose the 502s.  

Please note: enabling application insights analytics for a bot is different from configuring application insights for a web application
Bot: https://docs.microsoft.com/en-us/azure/bot-service/bot-service-manage-analytics?view=azure-bot-service-4.0#enable-analytics 
Web Application: https://docs.microsoft.com/en-us/azure/application-insights/app-insights-asp-net 

Please ensure you have enabled Application Insights both for the bot, and for the web application hosting the bot code.

**Comment by saurav2107** [comment]
Hi @EricDahlvang, thanks for clarifying.
One thing I would like you to know about the issue I am facing is, whenever I see this error, I do get the response, only problem is it takes around 15 to 30 seconds to get the response, I am not doing anything fancy in this, just a query to QnA Maker.

Please help, I am still getting these errors, and it really getting very annoying.

![image](https://user-images.githubusercontent.com/1011594/50280817-89227e00-0473-11e9-925f-fff199fa8ea8.png)

**Comment by saurav2107** [comment]
Hi @CoHealer ,

I have used application insight for Bot and QnAMaker.
As my bot client (Directline) is hosted on a SharePoint site, I don't have application insight enabled for Bot's client.

**Comment by EricDahlvang** [comment]
Hi @saurav2107 

We were not asking if you have setup Application Insights for the bot client, but we are asking if you have setup application insights for the Bot, AND for the web application hosting the bot:

Bot: https://docs.microsoft.com/en-us/azure/bot-service/bot-service-manage-analytics?view=azure-bot-service-4.0#enable-analytics

Web Application: https://docs.microsoft.com/en-us/azure/application-insights/app-insights-asp-net

If you have set these up correctly, you should be able to determine what dependency calls are taking so long to complete.

**Comment by EricDahlvang** [comment]
Please open a new issue if you are still experiencing problems.
